### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by velegip** [skyfms/hhvm-ext_dbase#1]
Hi

First error: /root/hhvm-ext_dbase/ext_dbase.cpp:26:45: fatal error: hphp/runtime/base/base-includes.h: No such file or directory
 #include "hphp/runtime/base/base-includes.h"

Then it changed to : hphp/runtime/ext/extension.h.

Then the second error:
[ 16%] Building CXX object CMakeFiles/dbase.dir/ext_dbase.cpp.o
/root/hhvm-ext_dbase/ext_dbase.cpp: In function ‘bool HPHP::dbase_add_or_replace_record(int, const HPHP::Variant&, boost::optional<long int>)’:
/root/hhvm-ext_dbase/ext_dbase.cpp:108:37: error: variable ‘HPHP::ArrayIter arr_it’ has initializer but incomplete type
     for (ArrayIter arr_it(arr_record); arr_it; ++arr_it, cur_f++) {
                                     ^
/root/hhvm-ext_dbase/ext_dbase.cpp: In function ‘HPHP::Variant HPHP::f_dbase_create(const HPHP::String&, const HPHP::Variant&)’:
/root/hhvm-ext_dbase/ext_dbase.cpp:326:35: error: variable ‘HPHP::ArrayIter arr_it’ has initializer but incomplete type
   for (ArrayIter arr_it(arr_fields); arr_it; ++arr_it, cur_f++, i++) {
                                   ^
/root/hhvm-ext_dbase/ext_dbase.cpp:328:29: error: variable ‘HPHP::ArrayIter field_it’ has initializer but incomplete type
     ArrayIter field_it(field);

Please try to fix it. Thank you.

HHVM: 
HipHop VM 3.12.0 (rel)
Compiler: tags/HHVM-3.12.0-0-g440e6a096b2db8a449b9690a72f2f1792530e86a
Repo schema: 033b8dedf4af99b892f2488b103a8d67a58ff816

**Comment by kristapsk** [comment]
Grrrr.... Facebook likes to break things (compatibility) with a new HHVM versions, most likely that is the cause of this. Will try to look at this when will have some more or less free time (we internally use older HHVM versions).
